# Generated by Django 5.2 on 2026-01-12 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero_inicial', models.IntegerField(default=0)),
                ('numero_final', models.IntegerField(default=0)),
                ('numero_actual', models.IntegerField(default=0)),
                ('numero_global', models.IntegerField(default=0)),
                ('Tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colas.tipo')),
            ],
        ),
    ]
